---
# tasks file for ansible-dnsmasq
- name: Install Dnsmasq
  package:
    name: dnsmasq
    state: present
  tags: dnsmasq

- name: Copy bannder hosts
  template:
    src: banner_add_hosts.j2
    dest: /etc/banner_add_hosts
    mode: 0644
  notify: restart dnsmasq
  tags:
    - config

- name: Set configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
    mode: 0644
  notify: restart dnsmasq
  tags:
    - dnsmasq
    - config

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
